//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoShop.IRepository
{
    using System;
    using System.Collections.Generic;
    
    
        using Model;
    
      /// <summary>
      /// 负责每个数据表的数据操作的约定
      /// </summary>
    public partial interface IT_ProductsRepository :IBaseRepository<T_Products>
    {
        #region 针对此表的特殊操作的约定写在此处
    
        #endregion
    }
}
