//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoShop.Services
{
    using System;
    using System.Collections.Generic;
    
    using IRepository;
    using Model;
    using IServices;
    
      /// <summary>
      /// 负责每个数据表的数据操作
      /// </summary>
    public partial class T_UserBaseInfoService :BaseService<T_UserBaseInfo>,IT_UserBaseInfoService
    {
    	IT_UserBaseInfoRepository dal;
    	#region 定义构造函数，接收autofac将数据仓储层的具体实现类的对象注入到此类中
    	public T_UserBaseInfoService(IT_UserBaseInfoRepository dal)
    	{
    		this.dal = dal;
    		base.baseDal = dal;
    	}

        public void UserLogin()
        {
            //throw new NotImplementedException();
        }
        #endregion


        #region 针对此表的特殊操作写在此处

        #endregion
    }
}
