//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoShop.Repository
{
    using System;
    using System.Collections.Generic;
    
    	using Model;
    	using IRepository;
    
      /// <summary>
      /// 负责每个数据表的数据操作
      /// </summary>
    public partial class T_AdminRepository :BaseRepository<T_Admin>,IT_AdminRepository
    {
    	#region 针对此表的特殊操作写在此处
    		
    	#endregion
    }
}
