//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryInfo()
        {
            this.T_OrderInfo = new HashSet<T_OrderInfo>();
        }
    
        public System.Guid F_DId { get; set; }
        public string F_DConsignee { get; set; }
        public string F_DAddress { get; set; }
        public string F_DTel { get; set; }
        public Nullable<bool> F_DIsDefault { get; set; }
    
        public virtual T_UserBaseInfo T_UserBaseInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OrderInfo> T_OrderInfo { get; set; }
    }
}
