//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CarouselFigure
    {
        public int Id { get; set; }
        public string Redirect { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
    
        public virtual T_Category T_Category { get; set; }
    }
}
