//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Category()
        {
            this.F_Id = 1000;
            this.F_ParentId = 0;
            this.T_Goods = new HashSet<T_Products>();
            this.T_CarouselFigure = new HashSet<T_CarouselFigure>();
        }
    
        public int F_Id { get; set; }
        public string F_CategoryName { get; set; }
        public Nullable<int> F_OrderValue { get; set; }
        public string F_Icon { get; set; }
        public int F_ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Products> T_Goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CarouselFigure> T_CarouselFigure { get; set; }
    }
}
