//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OrderInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_OrderInfo()
        {
            this.F_UnitPrice = 0F;
            this.T_Attributes = new HashSet<T_Attributes>();
        }
    
        public System.Guid Id { get; set; }
        public string F_Quantity { get; set; }
        public float F_UnitPrice { get; set; }
        public System.DateTime F_OrderTime { get; set; }
        public string F_OrderNumber { get; set; }
    
        public virtual T_UserBaseInfo T_UserBaseInfo { get; set; }
        public virtual T_OrderStatus T_OrderStatus { get; set; }
        public virtual T_Products T_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Attributes> T_Attributes { get; set; }
        public virtual DeliveryInfo DeliveryInfo { get; set; }
        public virtual T_Comment T_Comment { get; set; }
    }
}
