//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductAttr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ProductAttr()
        {
            this.Price = 0F;
            this.Stock = 0;
        }
    
        public int Id { get; set; }
        public float Price { get; set; }
        public int Stock { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
    
        public virtual T_Products T_Products { get; set; }
        public virtual T_Attributes T_Attributes { get; set; }
        public virtual T_AttrValue T_AttrValue { get; set; }
    }
}
