//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserDetailInfo
    {
        public System.Guid F_Id { get; set; }
        public string F_UNickName { get; set; }
        public Nullable<System.DateTime> F_UBirthday { get; set; }
        public string F_USex { get; set; }
        public string F_UTel { get; set; }
    
        public virtual T_UserBaseInfo T_UserBaseInfo { get; set; }
    }
}
